from aenum import enum


SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
MAX_FRAME_TIME = 6 * 1000 / FPS
RUN = True
KEY_FORCE = 1000
FRICTION = 3
ROTATION_FRICTION = 300


class ShapeType(enum):
    POLYGON = 0
    CIRCLE = 1


NEW_SHAPE_TYPE = ShapeType.POLYGON
NEW_SHAPE_RADIUS = 40
NEW_SHAPE_MASS = 10
NEW_SHAPE_DEGREE = 3
